In [4]:
import tensorflow as tf
a=tf.constant('hello world')
print(a.numpy())

b'hello world'


In [7]:
#Scalar constants
a=tf.constant(42)
b=tf.constant(16.3)
c=tf.constant('Hello Tensorflow!')
print(a)
print(a.numpy())
print(b)
print(b.numpy())
print(c)
print(c.numpy())

tf.Tensor(42, shape=(), dtype=int32)
42
tf.Tensor(16.3, shape=(), dtype=float32)
16.3
tf.Tensor(b'Hello Tensorflow!', shape=(), dtype=string)
b'Hello Tensorflow!'


In [9]:
#Vector constants
a=tf.constant([1,2,3])
print(a)
print(a.numpy())
a=tf.constant([1.3,2.4,3.6])
print(a)
print(a.numpy())

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
[1 2 3]
tf.Tensor([1.3 2.4 3.6], shape=(3,), dtype=float32)
[1.3 2.4 3.6]


In [13]:
#Matrix constants
a=tf.constant([[1,2],[4,5]])
print(a)
print(a.numpy())
a=tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print(a)
print(a.numpy())

tf.Tensor(
[[1 2]
 [4 5]], shape=(2, 2), dtype=int32)
[[1 2]
 [4 5]]
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
[[1. 2. 3.]
 [4. 5. 6.]]


In [19]:
#Higher dimensional tensor constant
a=tf.constant([[[1,2,3,4],[4,5,6,7]],[[1,6,8,3],[5,7,3,9]]])
print(a)
print(a.numpy())

tf.Tensor(
[[[1 2 3 4]
  [4 5 6 7]]

 [[1 6 8 3]
  [5 7 3 9]]], shape=(2, 2, 4), dtype=int32)
[[[1 2 3 4]
  [4 5 6 7]]

 [[1 6 8 3]
  [5 7 3 9]]]


In [16]:
#Boolean constant
a=tf.constant(True)
print(a)
print(a.numpy())

tf.Tensor(True, shape=(), dtype=bool)
True


In [20]:
#special constants
a=tf.zeros(shape=(2,2))
b=tf.ones(shape=(3,3))
print(a)
print(a.numpy())
print(b)
print(b.numpy())


tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
[[0. 0.]
 [0. 0.]]
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [22]:
tf.config.run_functions_eagerly(True)
a=tf.constant([[2,3],[1,2]])
b=tf.constant([[2,2],[2,2]])
c=tf.multiply(a,b)
result=a*b
print(result)
print(result.numpy())


tf.Tensor(
[[4 6]
 [2 4]], shape=(2, 2), dtype=int32)
[[4 6]
 [2 4]]


In [24]:
print(c)
print(c.numpy())

tf.Tensor(
[[4 6]
 [2 4]], shape=(2, 2), dtype=int32)
[[4 6]
 [2 4]]


In [28]:
c=tf.matmul(a,b)
print(c)
print(c.numpy())

tf.Tensor(
[[10 10]
 [ 6  6]], shape=(2, 2), dtype=int32)
[[10 10]
 [ 6  6]]


In [29]:
c=a@b
print(c)
print(c.numpy())

tf.Tensor(
[[10 10]
 [ 6  6]], shape=(2, 2), dtype=int32)
[[10 10]
 [ 6  6]]


In [31]:
a=tf.constant([[1,2,3],[3,4,5]])
a.get_shape()

TensorShape([2, 3])

In [33]:
a=tf.constant(1.25)
b=tf.cast(a,dtype=tf.int32)
print(a)
print(a.numpy())
print(b)
print(b.numpy())

tf.Tensor(1.25, shape=(), dtype=float32)
1.25
tf.Tensor(1, shape=(), dtype=int32)
1


In [38]:
a=tf.constant([[1.,2.,3.],[3.,4.,5.]])
b=tf.transpose(a)
print(b)
print(b.numpy())

tf.Tensor(
[[1. 3.]
 [2. 4.]
 [3. 5.]], shape=(3, 2), dtype=float32)
[[1. 3.]
 [2. 4.]
 [3. 5.]]


In [39]:
b=tf.reduce_sum(a)
print(b)
print(b.numpy())

tf.Tensor(18.0, shape=(), dtype=float32)
18.0


In [42]:
b=tf.concat([a,a,a],axis=0)
print(b.numpy())

[[1. 2. 3.]
 [3. 4. 5.]
 [1. 2. 3.]
 [3. 4. 5.]
 [1. 2. 3.]
 [3. 4. 5.]]


In [45]:
x=tf.constant([1.0,2.0,3.0])
logits=tf.constant([1.0,2.0,3.0])
softmax_probs=tf.nn.softmax(logits,axis=-1)
print(softmax_probs)

tf.Tensor([0.09003057 0.24472848 0.66524094], shape=(3,), dtype=float32)


In [46]:
softmax_probs=tf.nn.softmax(logits,axis=0)
print(softmax_probs)

tf.Tensor([0.09003057 0.24472848 0.66524094], shape=(3,), dtype=float32)


In [53]:
x=tf.constant([20.0,30.0,40.0,60.0,70.0])
logits = tf.constant([20.0, 30.0, 40.0, 60.0, 70.0])
softmax_probs=tf.nn.softmax(logits,axis=-1)
print(softmax_probs)

tf.Tensor([1.9286623e-22 4.2481610e-18 9.3571980e-14 4.5397868e-05 9.9995458e-01], shape=(5,), dtype=float32)
